[mypy]

[mypy-google]
ignore_missing_imports = True

[mypy-google.*]
ignore_missing_imports = True

[mypy-googleapiclient]
ignore_missing_imports = True

[mypy-googleapiclient.*]
ignore_missing_imports = True

[mypy-openpyxl]
ignore_missing_imports = True

[mypy-openpyxl.*]
ignore_missing_imports = True
